language: node_js

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - export CXX="g++-4.8"

node_js:
  - '4.2'
  - '5.0'

install:
  - npm install
  - npm install -g gulp
      # grok parser tests need node-grok
  - npm install node-grok@1.0.5

script:
  - gulp lint examples-check test-coverage

notifications:
  slack:
    secure: CIFuj0irasdPyw25bI+eimVL7RjFIVhjhjuBlHhTW5YW/G9gdR8l6KqEwrhM5gK9ff7Jf3QAyDXfJBszlRt26lD8tgjbbs9AF+DTmxN5zpDj4MiKSfxrstyyn7kCJ1ascE0cthVpu+/JgDhnSk2RMTPvUa+/p1Pl6PTjtzToEFUYMk/ovIdY1SPdllrLEZJlilbB4pCPMUuJfYqAvgF/oO7hjCmxKr+zHiUWHqy9xB1CZMVwUyQEJ2LG3E433S5f1ObCloi7oZmrO5CdBbLNEAM8DxT2ULPRL52BfmOcuzapYUOUWTtMsedCixzarC6Ux+25M9+vAxlp92pj+WlQacFCJw1YOT48raCkk8/Go8BL9pE4LyVOeuimCd7Qym5hCUTkhWrtFXeLY1WAQ1wuwOLS4LYaXO2Tb88OwO/jVzzgrwY36A+52Wa0OnNqvWiUue9S1guc70XaBi0IMVqPeykGKn9RWagUwREpXxonk5NUqo9Tjc3rEFpk77YhAQg8Ch63NQsG2gma6kA1hYP0psiwVxT579cbJXoF13vbVw2Hr673B29OT9snZv1692MQKZ0bd3+Au58woyEgMB8zkW9pevVWJgG/TWdMB35Pkks4t1+EGBatg694pbAOl+/Q7d17iL8Tm4NIpM0CV5MhRdqnqUwjDn+vP1Rm/+cVZCg=
